# 1) escolher a imagem base/
FROM nginx:latest

COPY index.html  /usr/share/nginx/html

#1) docker build -t carol/helo-nginx .
#2) docker images

#3) criar um container da minha imagem
#docker run -d carol/helo-nginx
#docker ps

#4) Como criar uma porta para acessar o container